const routes = {
  home: '/',
  deployContract: '/deploy-contract',
  setupRecovery: '/setup-recovery',
  guardianVote: '/guardian-vote',
  recoverAccount: '/recover-account',
  supportOthers: '/support-others',
  liquidity: '/liquidity',
  liquidityPosition: '/liquidity-position',
  farms: '/farms',
  farmsTwo: '/farms-2',
  createGoal: '/create-goal',
  claimNFT: '/claim-nft',
  nftDetails: '/nft-details',
  search: '/search',
  notification: '/notification',
  vote: '/vote',
  swap: '/swap',
  proposals: '/proposals',
  mygoals: '/my-goals',
  createProposal: '/proposals/create',
  charts: '/charts',
  mynfts: '/my-nfts',
  portfolio: '/profile?view=portfolio',
  history: '/profile?view=history',
};

export default routes;
